### ISSUE TITLE
Flexbox cheatsheet

### ISSUE THREAD

**Issue by genkio** [j1wu/kb#186]
![image](https://user-images.githubusercontent.com/5327840/49722311-d2224780-fca7-11e8-8610-b815edb66f77.png)

## Container
```css
.container {
    display: flex | inline-flex;
}
```

### Properties can be added to container

- flex-direction
- flex-wrap
- flex-flow
- justify-content
- align-items
- align-content

### flex-direction: decides the direction of main axis
```css
.container {
    flex-direction: row /*default*/ | row-reverse | column | column-reverse;
}
```

### flex-wrap: decides if items could be wrapped (go the the next line)
```css
.container {
    flex-wrap: nowrap /*default*/ | wrap | wrap-reverse;
}
```

### flex-flow: short cut for flex-direction and flex-wrap combo
```css
.container {
    flex-flow: <flex-direction> || <flex-wrap>; /* default: row nowrap */
}
```

### justify-content: decides how items should be aligned against main axis
```css
.container {
    justify-content: flex-start /*default*/ | flex-end | center | space-between | space-around;
}
```

#### Difference between space-between and space-around
![image](https://user-images.githubusercontent.com/5327840/49722624-845a0f00-fca8-11e8-8208-a1bf97c7194d.png)
![image](https://user-images.githubusercontent.com/5327840/49722645-8b811d00-fca8-11e8-8f87-4244eda4eee3.png)

### align-items: decides how items should be aligned against cross axis
```css
.container {
    align-items: flex-start | flex-end | center | baseline | stretch /* default, fill container height */;
}
```

### align-content: decides how wrapped items should be aligned against cross axis (applicable only when item wraps)
```css
.container {
    align-content: flex-start | flex-end | center | space-between | space-around | stretch /* default */;
}
```

### Properties can be added to item

- order
- flex-basis
- flex-grow
- flex-shrink
- flex
- align-self

### order: self explanatory
```css
.item {
    order: <integer>; /* default: 0 */
}
```

### flex-basis: content —> width —> flex-basis (limted by max|min-width)
```css
.item {
    flex-basis: <length> | auto /* default */;
}
```

### flex-grow: decides how the available space should be allocated to each item, item with flex-grow: 2 should be allocated 2 times of the space than others (if it's possible)
```css
.item {
    flex-grow: <number> /* default: 1 */;
}
```

### flex-thrink: same as flex-grow but the other way around
```css
.item {
    flex-shrink: <number> /* default: 0, and no negative number allowed */;
}
```

### flex: flex-grow, flex-shrink and flex-basis shortcut
```css
.item {
    flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
} 
```

### align-self: same as align-items but overwrites it
```css
.item {
   align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
```
